# start de compose command: docker compose -f docker-compose-backend.yml up -d
# stopt de container : docker compose -f docker-compose-backend.yml stop
# als je nieuwe backend code hebt gebruikt dit om nieuweste image draaien :
# docker compose -f docker-compose-backend.yml pull
# docker compose -f docker-compose-backend.yml up -d
# start en pull latest image command: docker compose -f docker-compose-backend.yml up -d --pull always

services:
  servesmart-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: servesmart-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${SA_PASSWORD}
    ports:
      - "14333:1433"
    volumes:
      - sql_data:/var/opt/mssql
      - ./db/init:/init
    healthcheck:
      test: /bin/bash -c "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P \"$$SA_PASSWORD\" -Q \"SELECT 1\""
      interval: 10s
      timeout: 5s
      retries: 20

  db-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    depends_on:
      servesmart-db:
        condition: service_healthy
    volumes:
      - ./db/init:/init
    entrypoint: ["/bin/bash", "-c"]
    command: >
      "/opt/mssql-tools18/bin/sqlcmd -C -S servesmart-db -U sa -P \"$$SA_PASSWORD\" -Q \"IF NOT EXISTS (SELECT 1 FROM servesmart_java_entitie.sys.tables) BEGIN PRINT 'INIT RUNNING' END\" &&
       /opt/mssql-tools18/bin/sqlcmd -C -S servesmart-db -U sa -P \"$$SA_PASSWORD\" -d master -i /init/00-init.sql || true"
    restart: "no"

  servesmart-backend:
    image: ghcr.io/jbaruba/servesmart-backend:latest
    container_name: servesmart-backend
    depends_on:
      db-init:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://servesmart-db:1433;databaseName=servesmart_java_entitie;encrypt=true;trustServerCertificate=true
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      APP_JWT_SECRET: ${APP_JWT_SECRET}
      APP_JWT_EXPIRATION_MS: ${APP_JWT_EXPIRATION_MS}

volumes:
  sql_data:
